### ISSUE TITLE
Gasket mount design

### ISSUE THREAD

**Issue by eksptt** [overset/JP01#2]
Similar to the recent Bear 65% (picture below), would like to try designing the Arisu layout with proper gasket mount system.

Changes to design would include; Reducing plate size and adding gasket mounting points, Adding gasket cutouts in the top case, and add protrusions around the edges of the bottom piece for gaskets.

![image](https://user-images.githubusercontent.com/85929925/123199930-6957ef00-d4e2-11eb-8c50-76f910c47d25.png)

**Comment by eksptt** [comment]
Also do note that ! do not know how to use any 3d software just yet.

**Comment by overset** [comment]
@eksptt it looks like you have a new account and welcome to Github!

The Bear65 is a nice and clean design for a similar layout to the Arisu, but completely different than the JP01 design. This would require designing the case from scratch and likely getting permission/blessing from the Bear65 designer and attribution where necessary.

I assume you are interested in exploring the design changes your self, but depending on your experience with designing for CNC work there could be a significant amount of learning and experimenting. One place to start is reviewing ai03's https://wiki.ai03.com/books/case-and-plate-design/page/brutally-honest-truths-of-designing-cases PSA.

I'll close this ticket since this would be a completely different design. Since the JP01 case is MIT licensed, derived work would be great even if it's learning from the poor design choices from this case.
